apiVersion: openstack.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-config-openstack
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: openstack-auth-config
      key: config
